# Site settings
title: "Arkane Network"
email: "info@arkane.network"
description: "Arkane.Network : Next generation blockchain wallet provider and developer api"
keywords: "arkane, arkane network, wallet, kyc, blockchain, wallet provider, blockchain api, ethereum, bitcoin, litecoin, tron, gochain, aeternity"
url: "https://arkane.network" # the base hostname & protocol for your site
twitter_username: fundrequest_io
github_username:  FundRequest
gtm_id: "GTM-P2JM2R2"
sass:
  sass_dir: _sass
  style: compressed

# Build settings
markdown: kramdown

exclude:
  - .git/
  - .github/
  - assets/scss/
  - build/
  - js/
  - node_modules/
  - scss/
  - vendor/
  - Gemfile
  - Gemfile.lock
  - package.js
  - package.json
  - package-lock.json
  - README.md

baseurl: "/" # the subpath of your site, e.g. /blog/
pagesurl: "/pages"
vendorsurl: "/assets/vendors"
imgurl: "/assets/img"
imageurl: "/assets/img"
cssurl: "/assets/css"
jsurl: "/assets/js"
